services:
  # Go 后端服务
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: ai-motion-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    networks:
      - ai-motion-network
    restart: unless-stopped

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: ai-motion-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - ai-motion-network
    restart: unless-stopped

networks:
  ai-motion-network:
    driver: bridge
